version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    #docker:
    #  - image: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
      - checkout

      - run:
          name: Installing Dependencies
          command: |
            wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
            sudo dpkg -i packages-microsoft-prod.deb
            rm packages-microsoft-prod.deb

            sudo apt-get update && sudo apt-get install -y dotnet-sdk-8.0
            sudo apt-get update && sudo apt-get install -y aspnetcore-runtime-8.0
      # Restore dependencies
      - run:
          name: Restore Dependencies
          command: dotnet restore

      # Build the project
      - run:
          name: Build Application
          command: dotnet build

      # Run tests (if any)
      - run:
          name: Run Tests
          command: | 
            dotnet test HelloWorld.Tests --no-build --nologo --results-directory:test_coverage \
            --collect:"Code Coverage" --verbosity n

      - store_test_results:
          path: ./HelloWorld.Tests/test-coverage

      - store_artifacts:
          path: ./HelloWorld.Tests/test-coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
