version: 2.1

orbs:
  mac: circleci/macos@2.5.2
  windows: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: mac/default

    steps:
      - checkout

      - run:
          name: Installing Dependencies
          command: |
            sudo apt update
            sudo apt install dotnet8

      # Restore dependencies
      - run:
          name: Restore Dependencies
          command: dotnet restore

      # Build the project
      - run:
          name: Build Application
          command: dotnet build

      # Run tests (if any)
      - run:
          name: Run Tests
          command: | 
            dotnet test HelloWorld.Tests --no-build --nologo --results-directory:test_coverage \
            --collect:"Code Coverage" --verbosity n

      - store_test_results:
          path: ./HelloWorld.Tests/test-coverage

      - store_artifacts:
          path: ./HelloWorld.Tests/test-coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
