version: 2.1

orbs:
  win: circleci/windows@4.1.1 # The Windows orb gives you everything you need to start using the Windows executor

jobs:
  build: # name of your job
    executor: win/server-2022 # use one of the executors defined within the windows orb
    steps:
      - checkout

      - run:
          name: Installing Chocolatey
          shell: powershell.exe
          command: |
            Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

      - run:
          name: Installing .NET SDK
          shell: powershell.exe
          command: |
            choco install dotnet-sdk --version=8.0.100 -y --no-progress

      - run:
          name: Installing ASP.NET Core Runtime
          shell: powershell.exe
          command: |
            choco install aspnetcore-runtime -y --no-progress

      # Restore dependencies for all projects
      - run:
          name: Restore Dependencies
          shell: powershell.exe
          command: dotnet restore

      # Build the main project and test project explicitly
      - run:
          name: Build All Projects
          shell: powershell.exe
          command: dotnet build --configuration Debug

      # Run tests
      - run:
          name: Run Tests
          shell: powershell.exe
          command: |
            dotnet test HelloWorld.Tests/HelloWorld.Tests.csproj --nologo --results-directory:test_coverage `
            --collect:"Code Coverage" --verbosity normal

      - store_test_results:
          path: ./HelloWorld.Tests/test-coverage

      - store_artifacts:
          path: ./HelloWorld.Tests/test-coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
