version: 2.1

orbs:
  win: circleci/windows@5.0.0

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

jobs:
  build:
    executor:
      name: win/default
    working_directory: C:\Users\circleci\project
    steps:
      - checkout
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - run:
          name: "Run Build step"
          command: dotnet.exe build
      - run:
          name: "Test the executable"
          command: |
            dotnet.exe test HelloWorld.Tests --no-build --nologo --results-directory:C:\Users\circleci\project\test_coverage --collect:"Code Coverage" --verbosity n
      - store_artifacts:
          path: C:\Users\circleci\project\test_coverage

      - store_test_results:
          path: C:\Users\circleci\project\test_coverage

      - store_artifacts:
          path: ./HelloWorld.Tests/test-coverage
