version: 2.1

executors:
  windows:
    machine:
      image: windows-server-2019

jobs:
  build:
    executor: windows
    steps:
      - checkout

      - run:
          name: Installing Dependencies
          command: |
            curl -L -o packages-microsoft-prod.deb https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
            Start-Process msiexec.exe -ArgumentList '/i', 'packages-microsoft-prod.deb', '/quiet', '/norestart' -Wait
            Remove-Item packages-microsoft-prod.deb

            choco install dotnet-sdk --version=8.0.100
            choco install aspnetcore-runtimepackagestore --version=8.0.100

      # Restore dependencies
      - run:
          name: Restore Dependencies
          command: dotnet restore

      # Build the project
      - run:
          name: Build Application
          command: dotnet build

      # Run tests (if any)
      - run:
          name: Run Tests
          command: |
            dotnet test HelloWorld.Tests --no-build --nologo --results-directory:test_coverage `
            --collect:"Code Coverage" --verbosity n

      - store_test_results:
          path: ./HelloWorld.Tests/test-coverage

      - store_artifacts:
          path: ./HelloWorld.Tests/test-coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
